"""Initial migration.

Revision ID: 4aa7448fb436
Revises: 
Create Date: 2024-12-19 12:58:26.175925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa7448fb436'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periodo', schema=None) as batch_op:
        batch_op.drop_index('cod_periodo_index')

    with op.batch_alter_table('registro_egresado', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='InnoDB; free: 37888 kB; InnoDB free: 8192 kB'
    )

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['nombre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id')

    with op.batch_alter_table('registro_egresado', schema=None) as batch_op:
        batch_op.create_table_comment(
        'InnoDB; free: 37888 kB; InnoDB free: 8192 kB',
        existing_comment=None
    )

    with op.batch_alter_table('periodo', schema=None) as batch_op:
        batch_op.create_index('cod_periodo_index', ['cod_periodo'], unique=False)

    # ### end Alembic commands ###
